[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "development" }
